Hyphenation update
koreader/crengine pull request #376
Opened 2020-09-11 09:31 UTC by roshavagarga

Covered some of the low-hanging fruit in #373 

Proposed changes:

- [x] Fixed hyphenmin in textlang.cpp based on http://www.hyphenation.org/tex#languages
- [x] Readded exceptions to Dutch hyphenation file
- [x] Readded exceptions to Irish hyphenation file
- [x] Readded exceptions to Norwegian hyphenation file
- [x] Readded exceptions to Portuguese hyphenation file
- [x] Readded exceptions to Slovak hyphenation file

2020-09-11 09:42 UTC, roshavagarga commented
@poire-z Should be good to go, unless I missed anything. Wasn't sure if I had to add any further changes to languages.json - I guesstimated that (2,2) is the default for hyphenmin or that it takes the information from textlang.cpp - if it's the former I should remove it from Serbian, while if it's the latter there's no need to have it at all, right? If none of the above, should I add hyphenmin for the other languages too?

2020-09-11 12:11 UTC, roshavagarga commented
Nothing else to add to this for now, so ready for review @poire-z @Frenzie

2020-09-11 12:53 UTC, Frenzie commented on crengine/src/textlang.cpp
> +    { "bg",       L"\x201e", L"\x201c", L"\x2019", L"\x2019", L"\x2018", L"\x2019" }, /* „ “ ’ ’ ‘ ’ */
I trust you on the hyphen stuff but this one's a tad problematic. ;-)
```
Error while processing /home/travis/build/koreader/crengine/crengine/src/textlang.cpp.

/home/travis/build/koreader/crengine/crengine/src/textlang.cpp:275:63: error: excess elements in struct initializer [clang-diagnostic-error]

    { "bg",       L"\x201e", L"\x201c", L"\x2019", L"\x2019", L"\x2018", L"\x2019" }, /* „ “ ’ ’ ‘ ’ */

                                                              ^

Found compiler error(s).
```

2020-09-11 12:55 UTC, NiLuJe commented on crengine/src/textlang.cpp
> +    { "bg",       L"\x201e", L"\x201c", L"\x2019", L"\x2019", L"\x2018", L"\x2019" }, /* „ “ ’ ’ ‘ ’ */
See the struct above, the code is only set up to handle 2 levels ;).

2020-09-11 13:19 UTC, roshavagarga commented on crengine/src/textlang.cpp
> +    { "bg",       L"\x201e", L"\x201c", L"\x2019", L"\x2019", L"\x2018", L"\x2019" }, /* „ “ ’ ’ ‘ ’ */
We can drop the second pair, third pair is the one that feels most natural and the only one I found an example of.

2020-09-11 13:27 UTC, roshavagarga commented on crengine/src/textlang.cpp
> +    { "bg",       L"\x201e", L"\x201c", L"\x2019", L"\x2019", L"\x2018", L"\x2019" }, /* „ “ ’ ’ ‘ ’ */
@Frenzie Should be a-okay now?

2020-09-11 15:56 UTC, Frenzie commented on crengine/src/textlang.cpp
> +    { "bg",       L"\x201e", L"\x201c", L"\x2019", L"\x2019", L"\x2018", L"\x2019" }, /* „ “ ’ ’ ‘ ’ */
Possibly, it says `[crengine/include/lvref.h:395]: (error) Reference to temporary returned.` but at a glance that doesn't seem to be related to this PR? The CI is there to avoid missing things though.

2020-09-11 18:14 UTC, cramoisi commented
@roshavagarga thanks for reverting the  French hyphenmin change :-) I studied it a lot and it need to be at 2,1 for processing some exceptions and weird french words within the limitation of crengine.

2020-09-11 18:49 UTC, poire-z commented
(I'll have a look at it over the weekend.)

2020-09-11 19:30 UTC, poire-z reviewed
Dunno if you wish to keep individual commits for each hyph dict - but if you do, please squash the commits related to textlang.cpp (at least the two that involve the hyphmin for FR and its revert).
(Not needed if you're fine with me squashing them all in a single commit.)

I still need to have a look at frontend, and if we can get rid of having a copy of the hyphmins stuff in frontend (by adding some function to fetch them from crengine).

2020-09-11 19:30 UTC, poire-z commented on cr3gui/data/hyph/languages.json
> +        "left_hyphen_min": 2,
(I don't think we use this languages.json anymore, but rather keep it correct.)
This highlighted `:` is probably because the previous line is missing a comma at the end: `"language": "en-GB",`

2020-09-11 19:39 UTC, poire-z commented on crengine/src/textlang.cpp
> +    { "bg",       L"\x201e", L"\x201c", L"\x2019", L"\x2019", L"\x2018", L"\x2019" }, /* „ “ ’ ’ ‘ ’ */
> it says `[crengine/include/lvref.h:395]: (error) Reference to temporary returned. `

That's strange. It said that too in https://travis-ci.org/github/koreader/crengine/builds/722519599 , but it exited with 0:
```
Checking crengine/src/textlang.cpp ...
Checking crengine/src/textlang.cpp: USE_FONTCONFIG=0;USE_FREETYPE=1;USE_HARFBUZZ=1;USE_FRIBIDI=1;USE_LIBUNIBREAK=1;USE_UTF8PROC=1;USE_NANOSVG=1;ALLOW_KERNING=1;CR3_PATCH=1;LINUX=1;_LINUX=1;CR_RENDER_32BPP_RGB_PXFMT=1;CR_EMULATE_GETTEXT=1;BUILD_LITE=0;LBOOK=0...
[crengine/include/lvref.h:395]: (error) Reference to temporary returned.
Running clang-tidy on crengine/src/textlang.cpp
The command ".ci/script.sh" exited with 0.
```

Oh, but that wasn't it. The exit status 1 is because of the missing comma in the json I mentionned below:
```
$ .ci/script.sh
parse error: Expected another key-value pair at line 24, column 5
Warning, json should reflect hyphenation patterns. Diff:
```

2020-09-11 20:06 UTC, cramoisi commented
IIRC, the crengine hyphenation method won't do anything with "tex hyphenation exception" as pattern with word without number in them like those that were added in Norwegian or Irish. If there is a numbered rule which applied for these words, they will be cut regardless they exist in these patterns..

`  <pattern>Stendhal</pattern>
   <pattern>Stendhals</pattern>
...

<pattern>bhrachtaí</pattern>
 <pattern>mbrachtaí</pattern>
 <pattern>cháintí</pattern>
 <pattern>gcáintí</pattern>
`

2020-09-11 22:04 UTC, roshavagarga commented on cr3gui/data/hyph/languages.json
> +        "left_hyphen_min": 2,
Feel free to squash everything, I'm pretty clueless on how to do that within web github.

2020-09-11 22:06 UTC, roshavagarga commented
@cramoisi Any idea how to make those full exceptions? I'm guessing those were added as-is because they're not supposed to be hyphenated at all. Will also accept any hints at how to handle lines that include `'` as Italian seems to be missing those :) <3

2020-09-11 22:24 UTC, cramoisi commented
@roshavagarga : before anything, checking if I'm wrong or not could be cool. After that if i'm wrong, nothing. If not, you just need to adjust the exception with a pattern with even number (odd : cut ; even : do not cut) in regard of the rules which already applied for these words. So if you got the <pattern>n1d</pattern> pattern, you will need to <pattern>Sten2dhal</pattern> (bigger number wins). It's very difficult to do it for a langage which is not yours. I did it for french but won't be able to do it for any other langage even if I can read some of them.

For line that include a `'`, you could do it as i did with french : crengine will take the `'` as a word separator so they will be processed as two distinct words. You need to look where these words need to be cut, and adjust the left or right hyphmin value. But it will have an impact on the rules already set. So you will need to rewrite or overwrite a bunch of them.

2020-09-12 05:47 UTC, roshavagarga commented
Okay, I have no idea what (odd : cut : even : do not cut means) - I thought you just had to prop down a 5 to denote segments where a word can be cut when it's a word :D

I'm only fluent in English and Bulgarian, so yeah, not really sure how to do it for others. As far as Italian - if I remember correctly there were no words, just short clusters with a `'`, including a line that's something like `2'2` which seemed even weirder. Does `'` function as a word separator too in TeX files or?

2020-09-12 06:03 UTC, poire-z commented on cr3gui/data/hyph/languages.json
> +    },
Some other complain by our json check script:
```
$ .ci/script.sh
parse error: Expected another key-value pair at line 24, column 5
```
Unlike in Lua, in JSON, a comma is not permitted at the end of the last `key: value`.
(Here and below in others ones like Croatian, English...)

2020-09-12 06:05 UTC, roshavagarga commented on cr3gui/data/hyph/languages.json
> +    },
Weren't those there beforehand?

2020-09-12 06:11 UTC, zwim commented
@roshavagarga: The tex hyphenation algorithm is described in https://tex.stackexchange.com/questions/262588/how-are-hyphenation-patterns-written ("The full explanation can be found in Appendix H of the TeXbook") and in https://en.wikipedia.org/wiki/Hyphenation_algorithm under References you can find some examples.

For German, it is easier to generate patterns, as there is a project on DANTE (http://projekte.dante.de/Trennmuster). The goal of this project is, to have a list of all preferable(!) hyphenations for every German word. Hyphenations which might lead to misunderstandings are dropped ((a good example is: "Urinstinkt" (engl. basic instinct) could be hyphenated in German like Ur-instinkt (correct) or Urin-stinkt (wrong: this means urine stinks ;-) ) ))

Maybe there are similar projects for other languages too.

2020-09-12 06:14 UTC, cramoisi commented
You mean you just add 5 and that’s all ? Without any other concern ? If you do the PR will potentially broke hyphen for these words if the file contain exception rules for them.

2020-09-12 06:16 UTC, roshavagarga commented
@cramoisi That's how they were done in the English files which did have exceptions, unlike the others, so I copied the method - if there was a `-`, replace it with a 5. I think none of the files had a number higher than that tbh.

2020-09-12 06:23 UTC, poire-z commented on cr3gui/data/hyph/languages.json
> +    },
Nope. You copied stuff (that wasn't at the end, so that had a comma) at the end. Or you removed stuff that was at the end, and so the remaining line (that wasn't at the end and had a comma) should have its comma removed (or stuff like that :)

2020-09-12 06:25 UTC, cramoisi commented
Ok perhaps I’m grumpy for not having a coffee already but I think this PR should be put « on hold » until somebody which understand how this is working within koreader/crengine could look at it. At first glance all these 5 should be checked and all pattern with nothing but letters are useless. So there are several file changes here that do nothing and will make the files difficult to understand to other people who will look at it. And yes maybe we have to document how it’s working since it’s not « as in libreoffice or tex »

2020-09-12 06:34 UTC, roshavagarga commented
@cramoisi No worries, coffee or no coffee I expected these to actually have some issues - If you humor me and explain like I'm 5, I could fix these on my own, within reason. Option B is reverting some of these or putting them in their own pull request, since I really do want to get some of the changes in for 2020.09 :)

2020-09-12 06:34 UTC, cramoisi commented
@roshavagarga : yup, but I did that while knowing why I did it :-) and I know 5 for these words is OK (and it was just a few words). Doing it bulkly for pattern you can't read and without knowing how that's work is far far more dangerous.

2020-09-12 06:36 UTC, roshavagarga commented on cr3gui/data/hyph/languages.json
> +    },
Sooo, yeah, which ones should I get rid of? (Haven't had my tea, brain isn't really sure which end you're talking about)

2020-09-12 06:41 UTC, roshavagarga commented
@cramoisi Oh no, this is definitely my bad, I thought that the whole xxxx5xxx5xxx5xx thing was a specific exception pattern/number, as in any word that follows that will not be affected by patterns using the other numbers and will only be hyphenated in the manner that is shown. If you want we can take this to gitter?

2020-09-12 06:41 UTC, Frenzie commented on cr3gui/data/hyph/languages.json
> +    },
In Lua, we prefer:

```lua
bla,
bla,
bla, -- trailing comma, smaller diffs, no need to think about commas
```

But in JSON, that should be:
```js
bla,
bla,
bla
```

2020-09-12 06:42 UTC, cramoisi commented
@roshavagarga : ok
2'2 pattern (and perhaps 2-2 pattern) in tex file should be ignored. It only says that you can't cut after or before an apostrophe (or hyphen) but crengine won't do that anyway. For the understanding of all this mess works, after you read zwim link, you could do this one [http://hunspell.sourceforge.net/tb87nemeth.pdf](http://hunspell.sourceforge.net/tb87nemeth.pdf) :-)

The five thing should be good, but the lines with no number are more problematics as you won't be able to make them work (as i explain above) without fully comprehend how all patterns work against each other.

2020-09-12 06:47 UTC, roshavagarga commented
@cramoisi I'll have to look into it a bit more I guess, since Italian is missing around 30 lines with an `'` symbol. Example:
We have `2ch.`, but don't have `2ch'.` or `2ch''.` in our pattern file.

Theoretically words that are presegmented can be kept, while the ones I can't do myself can just be commented out and left for someone fluent to actually fix?

2020-09-12 06:49 UTC, poire-z commented
> since I really do want to get some of the changes in for 2020.09 :)

This might be a bit too hurrying :) 2020.09 is probably due this weekend - and I'd like to cleanup readertypography and hyphmins while bumping it, which will take me a bit of time.

2020-09-12 06:51 UTC, roshavagarga commented
@poire-z 2020.10 it is then, but in that case I might add a few more languages we're missing altogether.

2020-09-12 06:54 UTC, cramoisi commented
>Theoretically words that are presegmented can be kept, while the ones I can't do myself can just be commented out and left for someone fluent to actually fix?
Yes :) 

>since Italian is missing around 30 lines with an ' 

I removed them because crengine cannot read them. For words with ' or '' you'll have to deal case by case as I did in french with aujourd'hui or presqu'ile, etc. There are only a little number of these words in french so i could easily do it with some adaptations like the right hyphenmin

2020-09-12 06:59 UTC, cramoisi commented
But some of them don't need to be in the pattern file `TeX 2ch'.` or `2ch''.` only says that you can't cut before ch' or ch''. As crengine won't deal with `'` or `''` you only need one rule (the one i left on purpose)

2020-09-12 07:15 UTC, poire-z commented
I can't find where @cramoisi previously explained all these things about the numbers :/ but there is such a post somewhere...
But just in case, to understand a bit how they work in crengine, there's some debugging output at https://github.com/koreader/crengine/pull/157#issuecomment-493738835 which might show a bit how this works internally.
(I don't want to have to look at the code to understand it again :)

2020-09-12 07:27 UTC, cramoisi commented
I remember a long discussion about this in a place about something else (humpf)...  but I found back https://github.com/koreader/koreader/issues/3848  where we discussed it the first time : - )

2020-09-12 08:58 UTC, cramoisi commented
@roshavagarga, @poire-z  (to sum up) :

0/ For any word, all the rules that apply to it are applied and the word is cut only if a odd number > even number.
like in this example where you could see two rules applied on the final `te`. One with 1 want to cut but the one with 4 wins over it and thus it's not cut.

```
TRACE word to hyphenate: ' secrète '
DEBUG Pattern matched: se 100 on secrète  000000000
DEBUG Pattern matched: cr 120 on crète  0000000
DEBUG Pattern matched: rè 100 on rète  200000
DEBUG Pattern matched: te  4000 on te  0000
DEBUG Pattern matched: te  4000 on te  4000
DEBUG Pattern matched: te 100 on te  4000
TRACE Hyphenate: se-crète  s0e1-c2r0è4t0e0
```

2/ The "5 exceptions" are OK only if there is no rule with an odd number > 5 in the file (or only if the segment determined with five are not the subject of a greater even rule. 

3/ For rule with `'` or `''`, there is nothing to be done as (for example)  `2t.` or `2t'.` or `2t''` are the same rule for crengine which is translated by `<pattern>2t </pattern>` (dot or apostrophe or quotation mark are translated by space which means beginning / end of word according to their place).

4/ If, in a given language, there is words which include apostrophe and if these word are exceptions to the rules already applied to them, they must be deal with some special patterns. That means testing and perhaps changing the hyphenmin which could mean leading to rule creation to avoid to introduced bad hyphenation in some words (like I did in the french.pattern for `aujourd'hui`, etc.). For crengine, `aujourd'hui` is two words : `aujourd` and `hui`. But `aujourd'hui` is cut `au-jour-d'hui` in french. Previous rules only admit `au-jourd'hui`, etc. I could ignore it but as it's a rather long word the layout seems always off to me when I encounter it.

4/ Rules with words without number are to be left out / commented for some  fluent people to edit/test etc. Basically you need to introduced new rules with greater even number to deal with them without breaking anything already in place. Just like the second point, but in reverse.

If you have some other question feel free to ask :-)

2020-09-12 13:48 UTC, cramoisi reviewed
Some of them will not work with MAX_PATTERN_SIZE in hyphman.cpp as they exceed the 16 value.

2020-09-12 13:55 UTC, poire-z commented
Don't we have it at 35 ?
https://github.com/koreader/crengine/blob/cf54e8461c8ac4ef9c097e2d76f2a90ba21c44de/crengine/src/hyphman.cpp#L66-L69

2020-09-12 13:56 UTC, cramoisi commented
My bad, I'm a wayback machine 🤖

2020-09-16 10:55 UTC, poire-z commented
Any news on this PR ? Still holding it?

Btw, we could add support for Esperanto:
https://www.mobileread.com/forums/showthread.php?p=4035269#post4035269
https://github.com/pok49/vortodivido

(We no more have a solution for user-made/added hyphenation patterns for languages not supported.
And I don't want yet to have to think about a solution for that :/)

2020-09-16 12:26 UTC, roshavagarga commented
@poire-z I see no reason not to add Esperanto, though I didn't get the solution part - if you could expand on that a bit more?

As far as the PR - I have no idea, I can make some of the changes, but I might need help with iffy parts, since I'm not a programmer and while I am a linguist, I don't have a strong interest in hyphenation.

2020-09-16 12:39 UTC, poire-z commented
> though I didn't get the solution part - if you could expand on that a bit more?

That was just a comment on this user's question on the forum: he wanted to add esperanto himself by just dropping a pattern file, which worked one year ago.
But since then, I added the typography stuff, and just dropping a .pattern file doesn't work anymore. 
We now need to hardcode new languages in crengine code :/

So, this person won't have a solution, except if we help him by adding and hardcoding esperanto in crengine (like you did for Basque).

> As far as the PR - I have no idea, I can make some of the changes, but I might need help with iffy parts, since I'm not a programmer and while I am a linguist, I don't have a strong interest in hyphenation.

I don't know much about the hyphenation pattern stuff and changes required and what @cramoisi thought shouldn't go in (every pattern files, or just some of them)?
But if you have a good idea of what is to keep without risk in this PR, and what is dubious (italian?, others?) and should be removed (from this PR, to be reworked later maybe), I can do the cleanup of the PR for you before merging it (provided you allowed "allow edit from maintainers" somewhere on the right of this github page I think).

2020-09-16 12:40 UTC, cramoisi commented
@roshavagarga : i can provide rules for the "exceptions" words for your PR (those in pattern without number in them) if somebody can provide me with their point of hyphen like in [this comment](https://github.com/koreader/crengine/pull/157#issuecomment-493738835) from @poire-z  because i don't have a development setup atm.

so it would require : identify the exception patterns, make a file for testing them with their already up-to-date hypen file. After that, the PR will be ok i think

2020-09-16 12:51 UTC, poire-z commented
For the things that we should wait for people better than us - which could make us ware fo years :) - the question is whether their unperfect state in this PR is better than the previous (current crengine) state, and if merging this PR as it is will make things worse - or still improve them a little.
We could then let the exceptions stuff commented, so people fluent in these languages could just edit it and add the number/cut points.

2020-09-16 12:59 UTC, cramoisi commented
> or still improve them a little.

That will be improvement anyway, irrelevant lines would be ignored even if not commented as they won't find words to make a rule

> We could then let the exceptions stuff commented, so people fluent in these languages could just edit it and add the number/cut points

We could, but I (or everybody) can do the exception patterns as it's only a matter of saying to crengine to invalidate previous rules applied on a word. There are only few exceptions in the file and there is no need to be able to read the word, in fact. TeX's way is only to put the word as it in a pattern. For crengine, it will be by adding a 7 at each hyphenation point. The only thing needed to be left out for fluent people is dealing with things like apostrophe words.

2020-09-16 13:09 UTC, roshavagarga commented
@poire-z I think that's always on for my PRs. I'll take a look at it in a few hours and fix what can be fixed or state what needs fixing with the help of @cramoisi

2020-09-16 14:03 UTC, poire-z commented
> irrelevant lines would be ignored even if not commented as they won't find words to make a rule

I'd rather then see them commented, with some comment explaining what's left to be done - than seeing them uncommented and (people, or us in a few years :) wondering if they apply or not and what to do or not, and if there's a bug or not.

2020-09-16 14:05 UTC, cramoisi commented
> I'd rather then see them commented, with some comment explaining what's left to be done - than seeing them uncommented and (people, or us in a few years :) wondering if they apply or not and what to do or not, and if there's a bug or not.

Agreed of course

2020-09-16 14:18 UTC, poire-z commented
> it's only a matter of saying to crengine to invalidate previous rules applied on a word. There are only few exceptions in the file 

There may be only a few exception words to check, but for each of them, finding out the rules (among the thousands of them) that would match that exception word is quite some work, isn't it ?

2020-09-16 14:30 UTC, cramoisi commented
> There may be only a few exception words to check, but for each of them, finding out the rules (among the thousands of them) that would match that exception word is quite some work, isn't it ?

nearly no work at all if you pass the word in a debug hyphenation crengine with lang tag around them. the crengine will show where it would hyphen so we only need to add the word  pattern with 7 at hyphen place. It's like you did for me with the cyber-words for french in the #157

2020-09-16 15:13 UTC, poire-z commented
> Hyphenate: cy-be-re|n-tre-prise 
> so the pattern to add for the exception would be `<pattern> cybe6ren6tre6prise </pattern>`

You seem to have forgotten one: `<pattern>` cy**6**be6ren6tre6prise `</pattern>`

2020-09-16 16:40 UTC, roshavagarga commented
@cramoisi @poire-z 
Current things that need to be looked at:

- [ ] [Dutch exceptions](https://github.com/koreader/crengine/pull/376/commits/6bc53a970793415440e35a1be52b6798d1a6aba6)
Might need to use 6 or above for these?
- [ ] [Irish exceptions](https://github.com/koreader/crengine/pull/376/commits/f2f19cac1aa91702dbf0d3ceb8ad942f4a7a8191)
A lot of these might be words that shouldn't be hyphenated at all, should use 6 or above for the rest?
- [ ] [Norwegian exceptions](https://github.com/koreader/crengine/pull/376/commits/92351f268f27e1cba40a2be6eb90d60bec275693)
Some of these seem like words that shouldn't be hyphenated, might need to use 8 or above for the rest?
- [ ] [Portuguese exceptions](https://github.com/koreader/crengine/pull/376/commits/49608a91e8bdeca03f74a6fdd6e781c082dfdf80)
Only 2 words here, foreign loanwords to be specific, easy edit, 6 or above?
- [ ] [Slovak exceptions](https://github.com/koreader/crengine/pull/376/commits/398b44551bf2974627fe90c5e06b006d2e58ea46)
Short list, a few non-hyphenated ones, others should use 6 or above?

For Dutch, Frenzie might be a good person to ping, I personally don't have immediate knowledge of any of the above languages. 

Besides these, #373 covers some more major things that might be okay to include here or in a new PR - fixing Greek (help from a native to tell us which pattern to use), updating the Spanish pattern to the 5.0 version and checking the missing parts for Russian and Ukrainian. [Portuguese](https://github.com/hyphenation/tex-hyphen/blob/fef563e7843cc5d41da24cc0a3ccfa9a256bbcf7/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-pt.tex#L371) is low-hanging fruit.

2020-09-16 17:06 UTC, Frenzie commented
@roshavagarga What's the question exactly? The numbers/linebreaks look sensible enough I suppose.

2020-09-16 17:11 UTC, roshavagarga commented
@Frenzie The changes to the Dutch file are basically me adding in some 'exceptions' with the proper way to hyphenate them (and done in an improper manner, but that'll get fixed). Basically, wherever I've placed a 5 is where a hyphenation should/could occur - have a quick glance ([easier to see it here](https://github.com/hyphenation/tex-hyphen/blob/master/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-nl.tex#L12788)) and confirm whether those seem proper to you. Also, if you have any additions that have personally irked you over the years (loanwords, etc) - feel free to share so that those can get added too, the file is fairly old, so it might actually be outdated if anything changes since 1996.

2020-09-16 17:12 UTC, cramoisi commented
It's not 6 or above it's 6 :) if 6 is the highest even number used in the file it will say : dot not cut there.

2020-09-16 17:15 UTC, cramoisi commented
I meant : pattern with 5 and other patterns with numbersare OK. 6 should be used only with words that are exception for not being cut aka : those with no number inside them as discussed with @poire-z rhis afternoon

2020-09-16 17:22 UTC, roshavagarga commented
@cramoisi 
Dutch - 0 uses of 6.
Irish - numerous uses of 6 across the file.
Norwegian - uses 6, 7, 8 and 9.
Portuguese - highest even number used is 4.
Slovak - uses 6, 7 and 8.

2020-09-16 17:43 UTC, roshavagarga commented
@poire-z Esperanto should be okay now, I think.

2020-09-16 18:17 UTC, poire-z commented
> Esperanto should be okay now, I think.

Thanks for taking care of all these languages :) 
Pinging @pok49 for info (and in case you have some other comments on the language like quotes, etc... best to keep track here than on mobileread).

2020-09-16 18:19 UTC, Frenzie commented
@roshavagarga Like I said those are fine. ;-)

2020-09-16 18:51 UTC, cramoisi requested changes

2020-09-16 18:51 UTC, cramoisi commented on cr3gui/data/hyph/Occitan.pattern
> +  <pattern>2z''</pattern>
you can remove these lines, crengine won't be able to deal with them. `'` or `''` is not a thing for it.

2020-09-16 19:06 UTC, cramoisi commented
What about putting together all patterns without number at the end of the files  and comment them, another PR ? 😅

2020-09-16 19:12 UTC, roshavagarga commented
@Cramoisi If everyone else is okay with doing that, I'm fine with fixing it in a future pattern. I'll need a tiny hint on how to properly comment them out though :)

Latest changes add Estonian, Georgian, Latvian, Lithuanian, Occitan and Welsh hyphenation patterns + fixes to their quotation marks where needed for those that don't want to browse through the changes.

2020-09-16 19:18 UTC, cramoisi commented
@roshavagarga : you comment them with : 
`<!--  commented line -->` or 
```
<!--
line1 of my block of commented lines
line2 of my block of commented lines
line3 of my block of commented lines
-->
```

it's just that to do the pattern we have to make an epub with all the word inside the non-numbered patterns + patching crengine to output the hyphenation then test everything. It look like another thing

2020-09-16 19:30 UTC, roshavagarga commented
@cramoisi Commented everything out, I think, that should wrap this PR up, since I don't plan on adding other patterns for now.
@poire-z Feel free to do your squashing magic if everything looks in order.

2020-09-16 19:34 UTC, cramoisi commented
@roshavagarga you don't need to comment your "5" exception patterns, they are right. Only the one with no number in them.

2020-09-16 19:37 UTC, roshavagarga commented
@cramoisi Welp, a bit more spam changes incoming. Is there anything else I missed or did wrong? Don't want to spam too much, despite the incoming squash.

2020-09-16 19:59 UTC, roshavagarga commented
@cramoisi Okay, hopefully **that** will be the last time I mess up, but I sincerely doubt it :D
Thanks for the help and guidance :) Same goes for everyone else in the PR

2020-09-17 07:43 UTC, poire-z commented
Can you check again if you granted maintainers permissions ?
```
$ git push -f roshavagarga roshavagarga/master
[...]
To https://github.com/roshavagarga/crengine
 ! [remote rejected]   roshavagarga/master -> roshavagarga/master (permission denied)
error: failed to push some refs to 'https://github.com/roshavagarga/crengine'
```
Unless there's something with your branch being `master` preventing such updates, dunno.

2020-09-17 07:50 UTC, roshavagarga commented
@poire-z Sent you a collaborator invitation, that should probably fix it?

2020-09-17 08:06 UTC, poire-z commented
I was able to push, and got this:
```
remote: Create a pull request for 'roshavagarga/master' on GitHub by visiting:
remote:      https://github.com/roshavagarga/crengine/pull/new/roshavagarga/master
```
But then, I'm a bit in unknown territories :) 

Initially, I get this, which seem to indicate I would create a new PR in koreader/crengine:
<kbd>![image](https://user-images.githubusercontent.com/24273478/93437882-cc21b780-f8cc-11ea-9dc0-9426b395d444.png)</kbd>

I could switch the left base repository to be your `roshavagarga/master`, but then, I don't know what will happen (there's that `can't auto merge` warning) but you might get a new PR that you can merge in your master - but I don't know if this will auto propagate and update this koreader/crengine PR :)
<kbd>![image](https://user-images.githubusercontent.com/24273478/93437956-e6f42c00-f8cc-11ea-85b5-d2d28113460e.png)</kbd>

Should I try that last idea (which if it fails, will just pollute your `roshavagarga/master`.

(I have your original work and my squashed work backed up - so we can end up trashing everything and making a new PR.)

2020-09-17 08:09 UTC, roshavagarga commented
Go ahead, and this pull request updates automatically from my master - and again I'm sorry, I tried learning git some time ago and just gave up out of frustration and stuck with using github's web ui.

2020-09-17 08:43 UTC, poire-z commented
Things didn't work out :/
So, squashed version of this PR made into a new PR: #378.

2020-09-17 12:28 UTC, NiLuJe commented
@poire-z: IIRC, things may be finicky when the PR is against (user's) master, because we *may* not be able to push there (as opposed to a topical branch).

Otherwise, just adding a remote on your end and dealing with it like any other branch works for this kind of stuff ;).

2020-09-17 13:14 UTC, poire-z commented
Done via #378, so closing this one unmerged.

2020-09-17 13:14 UTC, closed without merging

2020-10-05 06:18 UTC, virxkane commented
@roshavagarga 
> * Ping for an update to [CoolReader](https://github.com/buggins/coolreader/pull/125) (pkb?)
Updated in https://github.com/buggins/coolreader/pull/175

2020-10-05 06:21 UTC, roshavagarga commented
@virxkane You might be interested in #383 too. Thanks for the help :+1: