Hyphenation patterns update (cleaned up #376)
koreader/crengine pull request #378
Opened 2020-09-17 08:40 UTC by poire-z

See #376 for the whole discussion and work steps.
This is just #376 with the 33 work commits squashed into 17 logical commits.

2020-09-17 08:42 UTC, poire-z commented
Pinging @roshavagarga and @cramoisi (I can't add you as reviewers...) for a quick look and confirmation that I didn't mess anything, before merging.

2020-09-17 08:46 UTC, cramoisi commented
I will look into it after work :)

2020-09-17 08:48 UTC, roshavagarga commented on cr3gui/data/hyph/languages.json
> +        "right_hyphen_min": 2
I missed adding a comma after this line (157)

2020-09-17 08:50 UTC, poire-z commented on cr3gui/data/hyph/languages.json
> +        "right_hyphen_min": 2
Yup, just saw that, going to fix it.

2020-09-17 08:53 UTC, roshavagarga commented
I did my once-over and it seems fine to me, though I did notice this has 1 less new line compared to the original, but no idea where that 1 missing line is from, probably something I missed and you fixed?

2020-09-17 08:54 UTC, poire-z commented
Yes, a last trailing blank line in Esperanto.pattern that I removed (to avoid github highlighting it as "not clean").

2020-09-17 08:57 UTC, roshavagarga commented
Ah, those always annoyed me, good to know I can get rid of them :+1:

2020-09-17 09:35 UTC, poire-z commented
Added 2 commits to rename badly named Romanian and Ukrainian pattern files, and some methods to help cleaning up frontend readertypography.lua code.

2020-09-17 10:18 UTC, roshavagarga commented
@poire-z Not sure how to add changes to this PR, so I've attached the latest Spanish pattern :)

[Spanish.zip](https://github.com/koreader/crengine/files/5238257/Spanish.zip)

2020-09-17 10:45 UTC, poire-z commented
OK, added.

> I tried learning git some time ago and just gave up out of frustration and stuck with using github's web ui.

If you plan to do more work/fixes like these, and you have a linux machine / can do git command line stuff, I can give you a small cheatsheet on how to proceed to make simple PRs on new branches (that I could more easily reword, but even you, and we'll be here to help if you get stuck).

2020-09-17 10:49 UTC, roshavagarga commented
Yeah, the one Linux machine I have is a decrepit single-core tiny notebook from like 7-8 years ago that's running Lubuntu, because nothing else runs well on it :/
I generally stick to Windows 7, because gaming, but you can still share the cheatsheet and if I do resort to it I can always boot from a usb drive or something.

2020-09-17 11:00 UTC, cramoisi requested changes

2020-09-17 11:03 UTC, roshavagarga commented on cr3gui/data/hyph/Spanish.pattern
> +  <pattern> reunim</pattern>
Only the ones without numbers @ 4098, right?

2020-09-17 11:08 UTC, cramoisi commented on cr3gui/data/hyph/Spanish.pattern
> +  <pattern> reunim</pattern>
yes :)

2020-09-17 11:22 UTC, poire-z commented
(@roshavagarga : I'll do the requested modifications - later this afternoon.)

2020-09-17 11:28 UTC, poire-z commented
OK, some quick notes (build from my own notes, removing more complex and rare stuff):

```
FORK repo on github

CLONE AND SETUP UPSTREAM :
$ git clone https://github.com/yourname/crengine.git
$ git remote -v
$ git remote add upstream https://github.com/koreader/crengine.git
$ git remote -v
    origin  https://github.com/yourname/crengine.git (fetch)
    origin  https://github.com/yourname/crengine.git (push)
    upstream  https://github.com/koreader/crengine.git (fetch)
    upstream  https://github.com/koreader/crengine.git (push)

NEVER ADD STUFF TO YOUR master BRANCH, it will just be kept up to date
with upstream master as a reference.

To sync your local master branch with upstream:
$ git checkout master
$ git fetch upstream
$ git merge upstream/master
To update your remote branch with your now-sync'ed local branch:
$ git push origin master

----
CREATE A NEW BRANCH to be pushed as a PR:
$ git checkout -b my-mod-branch
<< edit files >>
To see your changed stuff
$ git status
$ git diff

To make a commit with your changed stuff:
$ git add path/to/file
$ git add .    (if you want to add them all)
$ git status
$ git commit
<< lauches vi >>
    Your commit title

    Your commit details if needed.
Check all looks good:
$ git log
$ git log -p
Add more commits if needed.

When ready, push for a PR
$ git push -u origin my-mod-branch         (-u to create it)
And follow the url to github to open a PR.

Add more commits (as above) if needed to answer review comments, and push them:
$ git push origin my-mod-branch

Here, you would have a lot of other options, to rebase, squash, remove commits,
I could detail them when needed.

When PR is merged, cleanup and resync everything:
$ git checkout master
$ git branch -D my-mod-branch
$ git fetch --prune
$ git fetch upstream ; git merge upstream/master
$ git push origin master

Ready for next PR :)
```

2020-09-17 11:39 UTC, poire-z commented on cr3gui/data/hyph/Spanish.pattern
> +  <pattern> reapríet</pattern>
All 4 ? Or just the last one without any number?

2020-09-17 11:40 UTC, poire-z commented on cr3gui/data/hyph/Spanish.pattern
> +  <pattern> reapríet</pattern>
I'll assume it's just the last one.

2020-09-17 11:41 UTC, poire-z commented on cr3gui/data/hyph/Spanish.pattern
> +  <pattern> reapríet</pattern>
Of, right, you answered that below :)

2020-09-17 11:44 UTC, cramoisi commented on cr3gui/data/hyph/Spanish.pattern
> +  <pattern> reapríet</pattern>
yup. only the non-numbered one. I messed with my line selection, sorry :)

2020-09-17 11:50 UTC, poire-z commented
Ok, done. Please have a quick look again as I did this in a hurry.

2020-09-17 11:57 UTC, cramoisi approved these changes
ok good for me :)

2020-09-17 12:02 UTC, roshavagarga approved these changes

2020-09-17 13:13 UTC, merged

2020-09-20 20:46 UTC, virxkane commented
This file is sufficient to describe the 'TeX Hyphenation patterns' format?
https://github.com/hyphenation/tex-hyphen/blob/master/docs/tb87nemeth.pdf

Ok, I can pick hyphenation patterns files from KOReader into CoolReader. Thanks to all contributors.
But I thought, what to do with the "``*_hyphen_(Alan) .pdb``" files, just delete it? But what if there is something missing in the "``*.pattern``" files?
So, I wrote a simple converter (dumper) for "``*_hyphen_(Alan).pdb``" or "``*.pattern``" files and saw that some of the patterns that are present in "``*_hyphen_(Alan).pdb``" are missing in "``*.pattern``".
I guess that "``*_hyphen_(Alan).pdb``" files transfered from AlReader program: https://github.com/koreader/crengine/blob/a00d1b8c26f4a621d805575a6a4cf10d81c8e7c7/crengine/src/hyphman.cpp#L2
And I don't know where Alan got these patterns and how correct they are.
But if I make dump from "``English_US_hyphen_(Alan).pdb``" I got 295799 bytes instead of 126141 from file ``English_US.pattern``. And this fact makes you wonder which file is better and more correct.
I found that in KOReader "``*_hyphen_(Alan).pdb``" files dropped in https://github.com/koreader/crengine/pull/209 and https://github.com/koreader/crengine/pull/206 and I guess nobody checked contents of the "``*_hyphen_(Alan).pdb``" files.
Maybe we can combine them somehow? What is the best way to do this? Is it ok to just add omitted patterns in "``*.pattern``" from "``*_hyphen_(Alan).pdb``"?

P.S. This tool can be found in my not-yet-merged branch here: https://github.com/virxkane/coolreader/tree/updates-2020.09-1/crengine/Tools/HyphDumper
I would be grateful if someone points out the errors.

2020-09-20 21:07 UTC, cramoisi commented
I could check the differences if you provide a human readable dump of English pdf file. But as now we are following the hyphen patterns from recognised sources, so I don't think we need to worry about trying to make better than linguists already did for libreoffice, etc. I think feedback from native speakers should be enough as it's somehow tricky to edit these files without in dept knowledge of the languages...

2020-09-20 21:18 UTC, virxkane commented
How can I make "human readable dump of English pdf file"? I can only convert ``*_hyphen_(Alan).pdb`` into ``*.pattern``.

2020-09-20 21:22 UTC, cramoisi commented
That will do as I'm human and I can read a pattern file with my eyes :)

Btw : I checked the content of pdb files back then but only for a few of them. As I said, some differences are legit

2020-09-20 21:29 UTC, poire-z commented
> Maybe we can combine them somehow? What is the best way to do this? Is it ok to just add omitted patterns in "*.pattern" from "*_hyphen_(Alan).pdb"?

I don't think combining them makes any sense: it's not really "the more items the better", but having a set that is consistent within itself (some patterns with numbers overriding some others with other numbers - mixing sources could possibly have these numbers relations incoherent).
Given that we don't really know who made the _Alan.pdb from what and when, and that the sources used to build the *.pattern are recent, referenced and updated, our *.pattern are a lot more trustable.

2020-09-21 05:12 UTC, virxkane commented
> I don't think combining them makes any sense: it's not really "the more items the better", but having a set that is consistent within itself (some patterns with numbers overriding some others with other numbers - mixing sources could possibly have these numbers relations incoherent).
> Given that we don't really know who made the _Alan.pdb from what and when, and that the sources used to build the *.pattern are recent, referenced and updated, our *.pattern are a lot more trustable.

Yes, it looks logical.
And finally, for the connoisseurs of English, which I am not, dump 4 files:
1. https://github.com/koreader/crengine/blob/master/cr3gui/data/hyph/English_GB.pattern ->
[English_GB_dump.pattern.zip](https://github.com/koreader/crengine/files/5253472/English_GB_dump.pattern.zip)
2. https://github.com/koreader/crengine/blob/master/cr3gui/data/hyph/English_US.pattern -> 
[English_US_dump.pattern.zip](https://github.com/koreader/crengine/files/5253473/English_US_dump.pattern.zip)
3. https://github.com/buggins/coolreader/blob/master/cr3gui/data/hyph/English_GB_hyphen_(Alan).pdb -> 
[English_GB_Alan_dump.pattern.zip](https://github.com/koreader/crengine/files/5253474/English_GB_Alan_dump.pattern.zip)
4. https://github.com/buggins/coolreader/blob/master/cr3gui/data/hyph/English_US_hyphen_(Alan).pdb -> 
[English_US_Alan_dump.pattern.zip](https://github.com/koreader/crengine/files/5253475/English_US_Alan_dump.pattern.zip)

The dump for "``*.pattern``" is the same as original, but all patterns are sorted for ease of comparison.
* Difference between "English_GB_Alan_dump.pattern" and "English_US_dump.pattern" is less than between "English_US_Alan_dump.pattern" and "English_US_dump.pattern" :).
* Patterns in "English_GB_hyphen_(Alan).pdb" like "a8s7s8o7c8i8a8t8e8s" look like a hack.

Is there something useful about these files "``*_hyphen_(Alan).pdb``" ?

2020-09-21 06:36 UTC, cramoisi commented
Ok, I checked and actual patterns are more developed and consistent than the old one. A good example is that exceptions introduced by the hacks you mentioned in the pdb files are all processed correctly in current pattern file. So I guess you could get rid of these _(alan).pdb files once for all :-)

2020-09-21 07:13 UTC, virxkane commented
@cramoisi Thank you.